links:
  minelist: https://minelist.kr/servers/16673-sarisam.kr
  minepage: 추천하시고 보상 받아가세요 
announce:
  enabled: false
  interval-seconds: 30
  message: '&a[알림]&f 마인리스트/마인페이지 추천 부탁드립니다! &e{minelist}&f / &b{minepage}'
reward:
  queue-offline: true
  allow-fuzzy-online-lookup: true
broadcast-on-reward:
  enabled: true
  message: '&a[추천]&f {player} 님이 &e{site}&f 추천 완료! &7[ 누적 추천수 {count_total} ] &7| &6마인리스트 매달 최다 추천 1위에게 &f1만 캐시 지급'
debug:
  log: true
rewards:
  slots:
    minelist:
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    minepage:
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
  data:
    minelist: []
    minepage: []
vote-reward:
  command-enabled: true
  command: '캐시 지급 {player} 50'
  player-message: '&a[추천]&f 추천 보상으로 &e{amount} 캐시&f가 지급되었습니다.'
monthly-reward:
  enabled: true
  reset-cumulative: true
  timezone: Asia/Seoul
  command: 캐시 지급 {player} 10000
  broadcast: '&e[추천] 지난달 1위 {player} ({count}회) — 10,000 캐시 지급!'
  tie-breaker: earliest

reset-countdown:
  enabled: true
  message: '&7[마인리스트 초기화까지 남은시간] &f{time}'
