name: UltimateRPS
main: com.minkang.ultimate.rps.UltimateRpsPlugin
version: 1.4.3
api-version: "1.16"
author: minkang
website: https://example.com/UltimateRPS
commands:
  rps:
    description: 가위바위보 시스템
    usage: /rps
    aliases: [가위바위보]
permissions:
  ultimaterps.use:
    default: true
    description: 가위바위보 이용 권한
  ultimaterps.admin:
    default: op
    description: 설치, 제거, 설정 등 관리자 권한
