name: Build (UltimateVotePlus)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 필요 시 모듈 루트로 이동하려면 아래 주석 해제하고 path 수정
      # - name: Set working directory
      #   run: echo "PROJECT_DIR=." >> $GITHUB_ENV

      - name: Setup Temurin JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      # 생성된 JAR 업로드 (upload-artifact v4 사용)
      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: UltimateVotePlus-jar
          path: |
            target/*.jar
          if-no-files-found: error
