name: Build (Java 11)

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build with Maven
        run: mvn -B -V -U -DskipTests package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.ref_name }}-${{ github.sha }}
          path: |
            target/*.jar
